version: 2
updates:
  # Only care about major updates to github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/scripts"
    schedule:
      interval: "daily"
# no support for c/cpp
