blank_issues_enabled: false
contact_links:
  - name: Official OrcaSlicer
    url: https://github.com/OrcaSlicer/OrcaSlicer
    about: This is an unofficial fork. For issues with official OrcaSlicer, please visit the main repository.
  - name: UnOfficial OrcaSlicer Wiki
    url: https://github.com/NanashiTheNameless/OrcaSlicer/wiki
    about: Check the wiki for documentation and guides.
