blank_issues_enabled: false
contact_links:
  - name: Discussion Forum
    url: https://github.com/NanashiTheNameless/OrcaSlicer/discussions
    about: Please raise ideas and feature suggestions here.
